### ISSUE TITLE
Migrate Issue Tracking to Zenhub

### ISSUE THREAD

**Issue by Jiros** [covidgraph/documentation#50]
At the moment we have several active issue trackers in a few repos 
* documentation (5 project boards)
* visual graph explorer 

The built in project level board appears to be manual in that you have to choose to add new issues as they are created. 

Zenhub allows us to automatically blend multiple repo issue trackers with new issues from any linked repo automatically being added to the backlog. Zenhub has sophisticated filters which should allow for all issues to live on the same board and to use filters to target relevant issues.

The general direction is for developer documentation and issues to live within individual repos.

Zenhub also allows users to choose a repo and to add new issues. We can create a series of templates across the repos to help with consistent information collection, labelling and assignment.

All contributors will need to be organisation members to grant them read access to all repos and we can use a team (or teams) to additionally grant them maintainer access to one or more repos. 

More information on Proposed approach can be found here:
https://github.com/covidgraph/documentation/wiki/Documentation

- [x] Update proposed approach document
- [x] Agree one or multiple teams
- [x] Add contributors to org + teams
- [ ] Agree template content (e.g. what should be in a bug request/etc)
- [ ] Add templates to repos

- [ ]

**Comment by Jiros** [comment]
Zenhub board live. Sent link to all inviting usernames.
Need to agree/add templates
